apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore-kubernetes
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: enableKubernetesSecretStore
    value: "true"
