apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-redis
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379" # Placeholder for local Redis host
  - name: redisPassword
    secretKeyRef:
        name: redis-password
        key: redis-password
  - name: enableTLS
    value: "false"
  - name: actorStateStore
    value: "true" # Required for actor state management
auth:
  secretStore: kubernetes # Or your configured secret store
