openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing Todo application tasks, including advanced features like recurring tasks, reminders, priorities, and tags.
servers:
  - url: http://localhost:8000/api/v1
    description: Local Development Server
paths:
  /tasks:
    get:
      summary: Retrieve a list of tasks
      description: Fetches all tasks for the authenticated user, with optional filtering and sorting.
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [ToDo, InProgress, Done, Cancelled]
          description: Filter tasks by status.
        - in: query
          name: priority
          schema:
            type: string
            enum: [Low, Medium, High, Critical]
          description: Filter tasks by priority.
        - in: query
          name: tags
          schema:
            type: array
            items:
              type: string
          description: Filter tasks by tags (comma-separated).
        - in: query
          name: search
          schema:
            type: string
          description: Full-text search across task titles and descriptions.
        - in: query
          name: sort_by
          schema:
            type: string
            enum: [created_at, due_date, priority, title]
          description: Field to sort tasks by.
        - in: query
          name: sort_order
          schema:
            type: string
            enum: [asc, desc]
            default: asc
          description: Sort order.
      responses:
        '200':
          description: A list of tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
    post:
      summary: Create a new task
      description: Allows an authenticated user to create a new task with various properties.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
  /tasks/{task_id}:
    get:
      summary: Retrieve a single task by ID
      parameters:
        - in: path
          name: task_id
          schema:
            type: string
            format: uuid
          required: true
          description: Unique identifier of the task.
      responses:
        '200':
          description: Task details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '404':
          description: Task not found
    put:
      summary: Update an existing task
      parameters:
        - in: path
          name: task_id
          schema:
            type: string
            format: uuid
          required: true
          description: Unique identifier of the task.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Task not found
    delete:
      summary: Delete a task
      parameters:
        - in: path
          name: task_id
          schema:
            type: string
            format: uuid
          required: true
          description: Unique identifier of the task.
      responses:
        '204':
          description: Task deleted successfully.
        '401':
          description: Unauthorized
        '404':
          description: Task not found
components:
  schemas:
    Task:
      type: object
      properties:
        task_id:
          type: string
          format: uuid
          readOnly: true
        user_id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
          example: Buy groceries
        description:
          type: string
          nullable: true
          example: Milk, eggs, bread
        due_date:
          type: string
          format: date-time
          nullable: true
          example: '2026-03-01T10:00:00Z'
        recurrence_pattern:
          type: string
          nullable: true
          example: 'daily'
        priority:
          type: string
          enum: [Low, Medium, High, Critical]
          default: Medium
        tags:
          type: array
          items:
            type: string
          nullable: true
          example: ['shopping', 'urgent']
        status:
          type: string
          enum: [ToDo, InProgress, Done, Cancelled]
          default: ToDo
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        completed_at:
          type: string
          format: date-time
          nullable: true
      required:
        - title
    TaskCreate:
      type: object
      properties:
        title:
          type: string
          example: Buy groceries
        description:
          type: string
          nullable: true
          example: Milk, eggs, bread
        due_date:
          type: string
          format: date-time
          nullable: true
          example: '2026-03-01T10:00:00Z'
        recurrence_pattern:
          type: string
          nullable: true
          example: 'daily'
        priority:
          type: string
          enum: [Low, Medium, High, Critical]
          default: Medium
        tags:
          type: array
          items:
            type: string
          nullable: true
          example: ['shopping', 'urgent']
      required:
        - title
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          example: Buy groceries
        description:
          type: string
          nullable: true
          example: Milk, eggs, bread
        due_date:
          type: string
          format: date-time
          nullable: true
          example: '2026-03-01T10:00:00Z'
        recurrence_pattern:
          type: string
          nullable: true
          example: 'daily'
        priority:
          type: string
          enum: [Low, Medium, High, Critical]
          default: Medium
        tags:
          type: array
          items:
            type: string
          nullable: true
          example: ['shopping', 'urgent']
        status:
          type: string
          enum: [ToDo, InProgress, Done, Cancelled]
          default: ToDo