// api-types.ts
//
// This file contains TypeScript interfaces for API responses and request bodies,
// mirroring the backend's OpenAPI specification for authentication and tasks.

/**
 * Interface for user registration request.
 */
export interface UserRegister {
  email: string;
  password: string;
}

/**
 * Interface for user login request.
 */
export interface UserLogin {
  email: string;
  password: string;
}

/**
 * Interface for the JWT token response.
 */
export interface Token {
  access_token: string;
  token_type: string;
}

/**
 * Priority levels for tasks
 */
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';

/**
 * Interface for a Task as returned by the API.
 */
export interface Task {
  id: string; // UUID string
  user_id: string; // UUID string
  title: string;
  description: string | null;
  completed: boolean;
  priority: TaskPriority;
  due_date: string | null; // ISO 8601 date string
  tags: string[]; // Array of tags
  created_at: string; // ISO 8601 date-time string
  updated_at: string; // ISO 8601 date-time string
}

/**
 * Interface for creating a new Task.
 * 'id', 'user_id', 'created_at', 'updated_at' are omitted as they are generated by the backend.
 */
export interface TaskCreate {
  title: string;
  description?: string | null; // Optional
  completed?: boolean; // Optional, defaults to false
  priority?: TaskPriority; // Optional, defaults to 'medium'
  due_date?: string | null; // Optional
  tags?: string[]; // Optional, defaults to empty array
}

/**
 * Interface for updating an existing Task.
 * All fields are optional for partial updates (PATCH/PUT).
 */
export interface TaskUpdate {
  title?: string;
  description?: string | null;
  completed?: boolean;
  priority?: TaskPriority;
  due_date?: string | null;
  tags?: string[];
}

/**
 * Interface for API error responses.
 */
export interface ApiError {
  detail: string | Array<{ loc: string[]; msg: string; type: string }>;
}